In [1]:
import cv2
import numpy as np
from PIL import Image
from keras import models

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Using TensorFlow backend.


In [2]:
#Load the saved model
#model = models.load_model('v2_last4_layers.h5')
model = models.load_model('v2_da_last4_layers.h5')

In [ ]:
video = cv2.VideoCapture(0)

#try
#video.set(3,640)
#video.set(4,480)

while True:
    _, frame = video.read()

    #Convert the captured frame into RGB
    im = Image.fromarray(frame, 'RGB')

    #Resizing into 224x224 because we trained the model with this image size.
    im = im.resize((224,224))
    img_array = np.array(im)

    #Our keras model used a 4D tensor, (images x height x width x channel)
    #So changing dimension 224x224x3 into 1x224x224x3 
    img_array = np.expand_dims(img_array, axis=0)

    #Calling the predict method on model to predict 'jab' on the image
    #{'block': 0, 'hook': 1, 'jab': 2, 'none': 3, 'slip': 4}
    temp = model.predict(img_array)
    print(temp)
    pred_block = model.predict(img_array)[0][0]
    pred_hook = model.predict(img_array)[0][1]
    pred_jab = model.predict(img_array)[0][2]
    pred_none = model.predict(img_array)[0][3]
    pred_slip = model.predict(img_array)[0][4]

    
    #if prediction is 1, which mean I am missing on the image, then show the frame in gray color.
    print(f'block: {pred_block},hook: {pred_hook},jab: {pred_jab},none: {pred_none},slip: {pred_slip}' )
    if pred_block>0.9:
        #frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(frame, 'block', (10,450), font, 3, (255, 0, 0), 2, cv2.LINE_AA)
    elif pred_hook>0.9:
        #frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(frame, 'hook', (10,450), font, 3, (255, 127, 0), 2, cv2.LINE_AA)
    elif pred_jab>0.9:
        #frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(frame, 'jab', (10,450), font, 3, (255, 255, 0), 2, cv2.LINE_AA)
    elif pred_none>0.9:
        #frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(frame, 'none', (10,450), font, 3, (0, 255, 0), 2, cv2.LINE_AA)
    elif pred_slip>0.9:
        #frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(frame, 'slip', (10,450), font, 3, (0, 0, 255), 2, cv2.LINE_AA)

        
    cv2.imshow("Capturing", frame)
    key=cv2.waitKey(1)
    if key == ord('q'):
        break
video.release()
cv2.destroyAllWindows()

[[0. 0. 0. 0. 1.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 1.0
[[0. 0. 0. 0. 1.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 1.0
[[0. 0. 0. 0. 1.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 1.0
[[0. 0. 0. 0. 1.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 1.0
[[0. 0. 0. 0. 1.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 1.0
[[0. 0. 0. 0. 1.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 1.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook

[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0.         0.         0.26975518 0.73024476 0.        ]]
block: 0.0,hook: 0.0,jab: 0.26975518465042114,none: 0.7302447557449341,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,ho

[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 0. 1. 0. 0.]]
block: 0.0,hook: 0.0,jab: 1.0,none: 0.0,slip: 0.0
[[5.686191e-38 0.000000e+00 0.000000e+00 1.000000e+00 0.000000e+00]]
block: 5.686191150614786e-38,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 0. 1. 0. 0.]]
block: 0.0,hook: 0.0,jab: 1.0,none: 0.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 0. 0. 0. 1.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 1.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook:

block: 1.0,hook: 0.0,jab: 0.0,none: 3.8208500032485053e-23,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.9876919e-14 0.0000000e+00]]
block: 0.0,hook: 1.0,jab: 0.0,none: 1.9876918985533773e-14,slip: 0.0
[[0.000000e+00 1.000000e+00 0.000000e+00 1.088168e-30 0.000000e+00]]
block: 0.0,hook: 1.0,jab: 0.0,none: 1.0881680039742766e-30,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0

block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none

block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 0. 1. 0. 0.]]
block: 0.0,hook: 0.0,jab: 1.0,none: 0.0,slip: 0.0
[[1. 0. 0. 0. 0.]]
block: 1.0,hook: 0.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 1. 0. 0. 0.]]
block: 0.0,hook: 1.0,jab: 0.0,none: 0.0,slip: 0.0
[[0. 0. 0. 1. 0.]]
block: 0.0,hook: 0.0,jab: 0.0,none: 1.0,slip: 0.0
[[7.026337e-07 9.999993e-01 0.000000e+00 0.000000e+00 0.000000e+00]]
block: 7.026337129900639e-07,hook: 0.9999992847442627